version: "3.8"
services:
  automation-rabbit:
    build:
      context: ./rabbit-mq-image
    container_name: automation-rabbit
    ports:
      - 15672:15672
      - 5672:5672
  automation-db:
     image: mariadb
     container_name: automation-db
     ports:
       - 3306:3306
     environment: 
                MARIADB_USER: pczech
                MARIADB_PASSWORD: pczech123
                MARIADB_ROOT_PASSWORD: root
                MARIADB_DATABASE: building_automation
  automation-backend:
      build:
        context: ./backend-image
      container_name: automation-backend
      ports:
       - 8080:8080
      depends_on:
              - "automation-rabbit"
              - "automation-db"
